In [1]:
import numpy as np

## Comparing performance with lists, etc.

In [2]:
N = 1000

In [3]:
%%time
list_ = list(range(N))
for i in range(N):
    list_[i] = list_[i] * list_[i]

Wall time: 0 ns


In [4]:
%%time
list_ = list(range(N))
list_ = [item * item for item in list_]

Wall time: 0 ns


In [5]:
%%time
list_ = list(range(N))
list_ = map(lambda x: x * x, list_)

Wall time: 0 ns


In [6]:
%%time
list_ = list(range(N))
list_sum = 0
for item in list_:
    list_sum += item

Wall time: 0 ns


In [7]:
%%time
list_ = list(range(N))
list_sum = sum(list_)

Wall time: 0 ns


In [8]:
%%time
arr = np.arange(N)
arr = arr * arr

Wall time: 0 ns


In [9]:
%%time
arr = np.arange(N)
arr_sum = np.sum(arr)

Wall time: 1 ms


Converting in to array gives a fast output
***

# Creating np Arrays

In [10]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [11]:
print(arr, type(arr))

[0 1 2 3 4] <class 'numpy.ndarray'>


In [12]:
arr = np.array([0.0, 2, 4, 6, 8])

In [13]:
print(arr, type(arr))

[0. 2. 4. 6. 8.] <class 'numpy.ndarray'>


In [14]:
arr

array([0., 2., 4., 6., 8.])

In [15]:
arr.dtype

dtype('float64')

In [16]:
arr.ndim

1

In [17]:
arr.shape

(5,)

In [18]:
arr.size

5

In [19]:
arr.itemsize

8

In [20]:
arr2d = np.array([
                  [1, 2, 3], 
                  [4, 5, 6]
])

In [21]:
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
arr2d.ndim

2

In [23]:
arr2d.shape

(2, 3)

In [24]:
arr2d.size

6

In [25]:
arr3d = np.array([
                  [
                   [1, 2, 3],
                   [4, 5, 6]
                  ],
                  [
                   [7, 8, 9], 
                   [10, 11, 12]
                  ]
])

In [26]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [27]:
arr3d.shape

(2, 2, 3)

In [28]:
arr3d.ndim

3

In [29]:
arr3d.size

12

In [30]:
np.ones((2, 3, 4))  # n,r,c

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [31]:
1729 * np.ones((2, 3, 4))

array([[[1729., 1729., 1729., 1729.],
        [1729., 1729., 1729., 1729.],
        [1729., 1729., 1729., 1729.]],

       [[1729., 1729., 1729., 1729.],
        [1729., 1729., 1729., 1729.],
        [1729., 1729., 1729., 1729.]]])

In [32]:
np.zeros((2, 3, 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [33]:
np.random.randn(2, 3) # Create random number with 2 rows and 3 cols. 

array([[-1.82601733, -0.98699593,  0.28705993],
       [-1.8927847 , -1.48095999, -0.00655038]])

In [34]:
np.random.rand(2, 3)

array([[0.13894564, 0.46026175, 0.62142289],
       [0.87000816, 0.13420504, 0.06690909]])

In [35]:
np.random.rand(10, 1) 

array([[0.82616902],
       [0.25607425],
       [0.30419213],
       [0.78356189],
       [0.08529152],
       [0.90612762],
       [0.62033514],
       [0.81574387],
       [0.27085198],
       [0.46047162]])

In [36]:
np.random.randint(10,20,(2,3)) # Creates random integers between 10 to 20 in the given shape (2,3)

array([[18, 13, 14],
       [10, 13, 15]])

In [37]:
np.arange(7, 71, 7) # creates a range from 7 to 70 not 71 due to the indexing rules with 7 intervals. 

array([ 7, 14, 21, 28, 35, 42, 49, 56, 63, 70])

In [38]:
np.linspace(7, 70, 10) # Creates evenly spaced range. 

array([ 7., 14., 21., 28., 35., 42., 49., 56., 63., 70.])

In [39]:
np.linspace(1,10) # default number of values is 50. 

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [40]:
np.array([True, False, True, True])

array([ True, False,  True,  True])

In [41]:
str_arr = np.array(['1.4', '2.1', '1.1'])

In [42]:
arr = np.array(str_arr, dtype='float')

In [43]:
print(arr,type(arr))

[1.4 2.1 1.1] <class 'numpy.ndarray'>


## indexing

In [44]:
arr3d = np.array([
                  [
                   [1, 2, 3],
                   [4, 5, 6]
                  ],
                  [
                   [7, 8, 9], 
                   [10, 11, 12]
                  ]
])

In [45]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [46]:
arr3d[1, 0, 0] # Array indexing 

7

In [47]:
arr3d[0,0,1]

2

In [48]:
arr3d[1, 0, 2]

9

In [49]:
i = 1
j = 0
k = 2
arr3d[i, j, k]

9

In [50]:
arr3d[1, :, :] 

array([[ 7,  8,  9],
       [10, 11, 12]])

In [51]:
arr3d[:, 1, :]

array([[ 4,  5,  6],
       [10, 11, 12]])

In [52]:
arr3d[:, :, 0:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[ 7,  8],
        [10, 11]]])

In [53]:
arr3d % 2 == 0

array([[[False,  True, False],
        [ True, False,  True]],

       [[False,  True, False],
        [ True, False,  True]]])

In [54]:
arr3d[arr3d % 2 == 1]

array([ 1,  3,  5,  7,  9, 11])

In [55]:
arr3d[(arr3d % 2 == 1) & (arr3d > 3)]

array([ 5,  7,  9, 11])

In [56]:
arr_slice = arr3d[:, :, 0:2]

In [57]:
print(type(arr_slice))

<class 'numpy.ndarray'>


In [58]:
arr_slice.ndim

3

In [59]:
arr_slice.shape

(2, 2, 2)

In [60]:
arr_slice[0, 0, 1]

2

In [61]:
arr_slice[0, 0, 0] = 1729

In [62]:
arr_slice

array([[[1729,    2],
        [   4,    5]],

       [[   7,    8],
        [  10,   11]]])

In [63]:
arr3d

array([[[1729,    2,    3],
        [   4,    5,    6]],

       [[   7,    8,    9],
        [  10,   11,   12]]])

In [64]:
arr_slice = np.copy(arr3d[:, :, 0:2])

In [65]:
arr_slice[0, 0, 0] = 1

In [66]:
arr_slice

array([[[ 1,  2],
        [ 4,  5]],

       [[ 7,  8],
        [10, 11]]])

In [67]:
arr3d

array([[[1729,    2,    3],
        [   4,    5,    6]],

       [[   7,    8,    9],
        [  10,   11,   12]]])

In [68]:
arr = np.random.randint(0, 10, (5))

In [69]:
arr

array([2, 9, 6, 7, 5])

In [70]:
my_indices = [1, 3, 4]

In [71]:
arr[my_indices]

array([9, 7, 5])

# Numpy Operations

In [72]:
arr1 = np.random.rand(3, 4)
arr2 = np.random.rand(3, 4)

In [73]:
arr1

array([[0.98415429, 0.4956701 , 0.42451341, 0.68551639],
       [0.19989403, 0.17883794, 0.18857078, 0.95235493],
       [0.29230123, 0.4310251 , 0.75553735, 0.54219263]])

In [74]:
arr2

array([[0.62767786, 0.00377217, 0.82403873, 0.11322484],
       [0.49133512, 0.70787217, 0.43337593, 0.69069998],
       [0.59677129, 0.41835908, 0.75292903, 0.73029736]])

In [75]:
arr1 + arr2

array([[1.61183215, 0.49944227, 1.24855214, 0.79874123],
       [0.69122915, 0.8867101 , 0.62194671, 1.6430549 ],
       [0.88907252, 0.84938418, 1.50846639, 1.27248999]])

In [76]:
arr1 - arr2

array([[ 0.35647643,  0.49189793, -0.39952531,  0.57229155],
       [-0.29144108, -0.52903423, -0.24480516,  0.26165495],
       [-0.30447007,  0.01266602,  0.00260832, -0.18810474]])

In [77]:
arr1 * arr2

array([[0.61773186, 0.00186975, 0.34981549, 0.07761748],
       [0.09821496, 0.1265944 , 0.08172204, 0.65779153],
       [0.17443698, 0.18032327, 0.56886601, 0.39596185]])

In [78]:
arr1 / arr2

array([[  1.56792895, 131.401902  ,   0.51516197,   6.05446992],
       [  0.40683848,   0.25264157,   0.43512055,   1.37882577],
       [  0.48980443,   1.03027547,   1.00346423,   0.7424272 ]])

In [79]:
np.exp(arr1)

array([[2.67554818, 1.64159791, 1.52884632, 1.9847965 ],
       [1.22127334, 1.19582693, 1.20752254, 2.59180599],
       [1.33950645, 1.53883417, 2.12875511, 1.71977356]])

In [80]:
np.log(np.exp(arr1))

array([[0.98415429, 0.4956701 , 0.42451341, 0.68551639],
       [0.19989403, 0.17883794, 0.18857078, 0.95235493],
       [0.29230123, 0.4310251 , 0.75553735, 0.54219263]])

In [81]:
np.sin(arr1)

array([[0.83280423, 0.47562121, 0.41187743, 0.63307283],
       [0.19856548, 0.17788616, 0.1874552 , 0.81478307],
       [0.2881566 , 0.41780236, 0.68567991, 0.51601539]])

In [82]:
np.cos(arr1)

array([[0.55356762, 0.87965019, 0.91123926, 0.77409224],
       [0.98008762, 0.98405107, 0.98227315, 0.57976594],
       [0.9575833 , 0.90853794, 0.72790319, 0.85657931]])

In [83]:
np.sqrt(arr1)

array([[0.99204551, 0.70403842, 0.65154694, 0.82795917],
       [0.44709511, 0.42289235, 0.43424737, 0.97588674],
       [0.54064889, 0.65652502, 0.86921652, 0.73633731]])

In [84]:
arr_inv = 1 / arr1

In [85]:
arr_inv

array([[1.01610084, 2.01747089, 2.35563817, 1.45875433],
       [5.00265056, 5.59165475, 5.30304867, 1.05002869],
       [3.42112831, 2.3200505 , 1.3235613 , 1.84436296]])

In [86]:
arr1 = np.zeros((3, 5))

In [87]:
arr_inv = 1/arr1

C:\Users\akilm\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


In [88]:
print(arr_inv)

[[inf inf inf inf inf]
 [inf inf inf inf inf]
 [inf inf inf inf inf]]


In [89]:
np.isinf(arr_inv[0,0])

True

In [90]:
np.isinf(arr_inv)

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

# Broadcasting

In [91]:
arr1 = np.arange(6)

In [92]:
arr1

array([0, 1, 2, 3, 4, 5])

In [93]:
arr1.shape

(6,)

In [96]:
arr1 = arr1.reshape((3, 2))
arr1

array([[0, 1],
       [2, 3],
       [4, 5]])

In [97]:
arr1.shape

(3, 2)

In [99]:
arr2 = np.arange(6).reshape((3, 2))
arr2

array([[0, 1],
       [2, 3],
       [4, 5]])

In [100]:
arr1 + arr2

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [103]:
arr2[0]

array([0, 1])

In [102]:
arr2[0].reshape((1, 2))

array([[0, 1]])

In [104]:
arr1 + arr2[0].reshape((1, 2)) # (3, 2) + (1, 2)

array([[0, 2],
       [2, 4],
       [4, 6]])

In [105]:
arr2[:, 0].reshape((3, 1))

array([[0],
       [2],
       [4]])

In [106]:
arr1 + arr2[:, 0].reshape((3, 1)) # (3, 2) + (3, 1)

array([[0, 1],
       [4, 5],
       [8, 9]])

In [107]:
arr1 + 1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [108]:
arr1 = np.arange(24).reshape((2, 3, 4))

In [109]:
arr1

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [110]:
arr2 = np.ones((1, 4))

In [111]:
arr1 + arr2   # (2, 3, 4) + (1, 4)

array([[[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]],

       [[13., 14., 15., 16.],
        [17., 18., 19., 20.],
        [21., 22., 23., 24.]]])

In [112]:
arr1 = np.arange(4)

In [113]:
arr2 = np.arange(5)

In [114]:
print(arr1.shape, arr2.shape)

(4,) (5,)


In [115]:
arr1 + arr2 # array needs to be of same size 

ValueError: operands could not be broadcast together with shapes (4,) (5,) 

In [116]:
arr1.reshape(4, 1) + arr2  # (4, 1) + (5)

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [117]:
arr = np.random.rand(3, 3)

In [118]:
arr

array([[0.05842266, 0.02416775, 0.51356518],
       [0.42052753, 0.66566039, 0.84476784],
       [0.01542207, 0.77557677, 0.48993521]])

In [119]:
arr.T

array([[0.05842266, 0.42052753, 0.01542207],
       [0.02416775, 0.66566039, 0.77557677],
       [0.51356518, 0.84476784, 0.48993521]])

# File handling

In [121]:
planets_small = np.loadtxt("planets_small.txt")

ValueError: could not convert string to float: 'MERCURY'

In [0]:
planets_small = np.loadtxt("planets_small.txt", 
                           skiprows = 1)

ValueError: ignored

In [122]:
planets_small = np.loadtxt("planets_small.txt", 
                           skiprows = 1,
                           usecols = (1, 2, 3, 4, 5, 6, 7, 8, 9))

In [123]:
planets_small

array([[3.3000e-01, 4.8700e+00, 5.9700e+00, 6.4200e-01, 1.8980e+03,
        5.6800e+02, 8.6800e+01, 1.0200e+02, 1.4600e-02],
       [5.7900e+01, 1.0820e+02, 1.4960e+02, 2.2790e+02, 7.7860e+02,
        1.4335e+03, 2.8725e+03, 4.4951e+03, 5.9064e+03],
       [4.2226e+03, 2.8020e+03, 2.4000e+01, 2.4700e+01, 9.9000e+00,
        1.0700e+01, 1.7200e+01, 1.6100e+01, 1.5330e+02]])

In [126]:
planets_small.shape
planets_small

array([[3.3000e-01, 4.8700e+00, 5.9700e+00, 6.4200e-01, 1.8980e+03,
        5.6800e+02, 8.6800e+01, 1.0200e+02, 1.4600e-02],
       [5.7900e+01, 1.0820e+02, 1.4960e+02, 2.2790e+02, 7.7860e+02,
        1.4335e+03, 2.8725e+03, 4.4951e+03, 5.9064e+03],
       [4.2226e+03, 2.8020e+03, 2.4000e+01, 2.4700e+01, 9.9000e+00,
        1.0700e+01, 1.7200e+01, 1.6100e+01, 1.5330e+02]])

# Stats with NumPy

In [128]:
arr = np.random.rand(100,) # randn gives random numbers between the standard distribution.

In [130]:
arr

array([0.90430898, 0.16828103, 0.75238602, 0.83608284, 0.36004341,
       0.65930148, 0.55627347, 0.70550565, 0.87428361, 0.4971382 ,
       0.98805603, 0.35976365, 0.61741024, 0.02496295, 0.43446519,
       0.24249218, 0.03133198, 0.74936736, 0.30926646, 0.95064841,
       0.90697432, 0.0776065 , 0.49669774, 0.92084516, 0.64170387,
       0.52227375, 0.97571986, 0.14379939, 0.2102494 , 0.93322085,
       0.13386082, 0.02839854, 0.56550409, 0.76840902, 0.29191979,
       0.5103485 , 0.83278316, 0.72339689, 0.24326109, 0.24508285,
       0.91793553, 0.48504498, 0.66077497, 0.49274999, 0.21587472,
       0.6272538 , 0.70417772, 0.56709935, 0.15164107, 0.94307164,
       0.7874485 , 0.30698479, 0.56513914, 0.02782161, 0.25872118,
       0.58546542, 0.07672116, 0.48703944, 0.13926076, 0.8804585 ,
       0.94947246, 0.11127637, 0.63343377, 0.79271312, 0.11733247,
       0.75660084, 0.19692568, 0.72569494, 0.517704  , 0.3828792 ,
       0.34634682, 0.45817875, 0.691804  , 0.09741324, 0.89896

In [131]:
np.amin(arr) # measure of centrality

0.024962948442477817

In [132]:
np.amax(arr) # measure of centrality

0.9880560269043186

In [134]:
np.mean(arr) # measure of centrality

0.5051451739590579

In [135]:
np.var(arr) # measure of spread

0.08881461201088914

In [136]:
np.std(arr) # measure of spread

0.29801780485549706

In [137]:
np.median(arr) # measure of centrality

0.5277188262427819

In [138]:
np.percentile(arr, 50) # measure of spread - 50th percentile

0.5277188262427819

In [139]:
np.percentile(arr, 10)# measure of spread

0.09640493834246791

In [140]:
np.percentile(arr, 90) # measure of spread

0.9019088021799113

In [146]:
%%time
iqr = np.percentile(arr, 75) - np.percentile(arr, 25)
print(iqr)

0.5389713319895126
Wall time: 966 µs


In [147]:
%%time
quartiles = np.percentile(arr, [25, 75])
iqr = quartiles[1] - quartiles[0]       # by indexing


print(quartiles)

print(iqr)

[0.21446839 0.75343972]
0.5389713319895126
Wall time: 1 ms


In [148]:
(arr - np.mean(arr))/np.std(arr)

array([ 1.33939584, -1.13034907,  0.82961769,  1.11046275, -0.48688958,
        0.51727213,  0.17156121,  0.67231042,  1.23864556, -0.02686745,
        1.6204094 , -0.48782833,  0.37670591, -1.61125348, -0.23716697,
       -0.88133321, -1.58988217,  0.81948857, -0.65727185,  1.49488797,
        1.3483394 , -1.43460781, -0.02834541,  1.39488307,  0.45822329,
        0.05747501,  1.57901534, -1.21249729, -0.98952403,  1.43640974,
       -1.24584621, -1.59972533,  0.2025346 ,  0.88338294, -0.71547867,
        0.0174598 ,  1.09939065,  0.73234454, -0.87875313, -0.87264023,
        1.38511978, -0.06744628,  0.52221644, -0.0415921 , -0.97064822,
        0.40973599,  0.66785455,  0.2078875 , -1.18618453,  1.46946411,
        0.94726999, -0.66492801,  0.20131   , -1.60166124, -0.82687675,
        0.26951492, -1.43757858, -0.06075385, -1.2277267 ,  1.25936544,
        1.49094207, -1.32162843,  0.43047291,  0.96493547, -1.30130717,
        0.84376056, -1.03423181,  0.74005566,  0.0421412 , -0.41

In [149]:
np.histogram(arr)

(array([15, 11,  8,  4,  8, 11,  9, 14,  7, 13], dtype=int64),
 array([0.02496295, 0.12127226, 0.21758156, 0.31389087, 0.41020018,
        0.50650949, 0.6028188 , 0.6991281 , 0.79543741, 0.89174672,
        0.98805603]))

In [150]:
np.histogram(arr, bins=5)

(array([26, 12, 19, 23, 20], dtype=int64),
 array([0.02496295, 0.21758156, 0.41020018, 0.6028188 , 0.79543741,
        0.98805603]))

In [151]:
np.histogram(arr, bins=[0, 0.25, 0.5, 0.75, 1])

(array([30, 16, 28, 26], dtype=int64), array([0.  , 0.25, 0.5 , 0.75, 1.  ]))

In [152]:
bins = [0, 0.25, 0.5, 0.75, 1]

In [153]:
np.digitize(arr, bins)

array([4, 1, 4, 4, 2, 3, 3, 3, 4, 2, 4, 2, 3, 1, 2, 1, 1, 3, 2, 4, 4, 1,
       2, 4, 3, 3, 4, 1, 1, 4, 1, 1, 3, 4, 2, 3, 4, 3, 1, 1, 4, 2, 3, 2,
       1, 3, 3, 3, 1, 4, 4, 2, 3, 1, 2, 3, 1, 2, 1, 4, 4, 1, 3, 4, 1, 4,
       1, 3, 3, 2, 2, 2, 3, 1, 4, 1, 1, 3, 1, 3, 1, 2, 1, 1, 4, 3, 1, 4,
       3, 1, 4, 1, 4, 3, 3, 4, 3, 1, 4, 3], dtype=int64)

In [154]:
arr1 = np.random.randint(0, 10, (10))

In [155]:
arr1

array([2, 4, 5, 8, 4, 7, 8, 0, 7, 4])

In [156]:
bins = [0, 6, 10]

In [157]:
np.digitize(arr1, bins) # Return the indices of the bins

array([1, 1, 1, 2, 1, 2, 2, 1, 2, 1], dtype=int64)

In [159]:
np.digitize(arr1, bins, right=True)

array([1, 1, 1, 2, 1, 2, 2, 0, 2, 1], dtype=int64)

In [160]:
arr1 = np.random.randint(50, 80, 100) # weight

In [161]:
arr2 = np.random.randint(150, 185, 100) # heights

In [162]:
arr3 = np.random.randint(17, 22, 100) # age

In [163]:
np.concatenate((arr1, arr2, arr3)).shape

(300,)

In [164]:
np.vstack((arr1, arr2, arr3)).shape

(3, 100)

In [165]:
arr2d = np.vstack((arr1, arr2, arr3))

In [166]:
np.amin(arr2d, axis=1)

array([ 50, 150,  17])

In [167]:
np.amax(arr2d, axis=1)

array([ 79, 184,  21])

In [168]:
np.mean(arr2d, axis=1)

array([ 64.67, 166.08,  18.96])

# Checking stats rules with numpy

## Mean subracted array has zero mean

In [171]:
arr = np.random.rand(100)
arr

array([0.40808268, 0.23459066, 0.12643258, 0.60918008, 0.14295822,
       0.37066625, 0.64802848, 0.85492856, 0.23622609, 0.4641332 ,
       0.13227385, 0.5337433 , 0.12067452, 0.99550501, 0.66121367,
       0.4736499 , 0.3127566 , 0.00703105, 0.61764677, 0.50401485,
       0.08771751, 0.9954337 , 0.98330233, 0.66821242, 0.09226804,
       0.12931166, 0.45558236, 0.75809121, 0.52656366, 0.98943096,
       0.70918826, 0.20891337, 0.57206479, 0.65403975, 0.28967052,
       0.17317   , 0.2931737 , 0.6829128 , 0.68333436, 0.9238367 ,
       0.44352045, 0.55410701, 0.86478682, 0.18642538, 0.54354719,
       0.54900884, 0.8304359 , 0.69809541, 0.51287932, 0.33957598,
       0.53536251, 0.8100358 , 0.05987634, 0.65729463, 0.4583875 ,
       0.07103519, 0.79470887, 0.60372437, 0.44950388, 0.744529  ,
       0.64436909, 0.09572082, 0.39225563, 0.58353246, 0.75875314,
       0.98702693, 0.16017749, 0.09678427, 0.81119894, 0.31892722,
       0.1117118 , 0.54670339, 0.92974634, 0.245798  , 0.98918

In [173]:
mean = np.mean(arr)
mean

0.4853376334524343

In [177]:
arr1 = arr - mean
arr1
np.mean(arr1)

1.1102230246251566e-17

## Computing mean with smaller set of values

In [178]:
arr = np.random.rand(1000)

In [179]:
for k in range(1, 50):
    arr1 = arr[0:k]
    print(k, np.mean(arr1))

1 0.7051072042651707
2 0.8235446949294416
3 0.7517448290291883
4 0.7968726805144799
5 0.8217899796844528
6 0.7062109849653314
7 0.6418112748672024
8 0.6732260864541486
9 0.6850938724974003
10 0.6618681428736412
11 0.6691677132262535
12 0.6718730358893327
13 0.6649276697168685
14 0.6865016877888267
15 0.6602474453223568
16 0.6475243727419788
17 0.6474968704249076
18 0.6662354661664119
19 0.6316030712752272
20 0.6040521953252224
21 0.5999853329327003
22 0.5739940793013365
23 0.5604483144630589
24 0.5704954242650612
25 0.5869583743980246
26 0.5851719675375241
27 0.587576522135399
28 0.5837335612156271
29 0.5962371938924811
30 0.5825778149974142
31 0.5721034887179666
32 0.5627582021699297
33 0.5541858449037884
34 0.5531377098003967
35 0.5535512706547004
36 0.5428396423390628
37 0.5366011190009727
38 0.5265335813951211
39 0.5315997259876653
40 0.5408665309499197
41 0.5398424838939466
42 0.5455596829506227
43 0.5415541445889198
44 0.5341531977484985
45 0.5272148638566666
46 0.527763050010399

In [181]:
np.cumsum # cumulative sum 

<function numpy.cumsum(a, axis=None, dtype=None, out=None)>

In [182]:
means = np.cumsum(arr)/np.arange(1,1001)

In [183]:
means[0:15]

array([0.7051072 , 0.82354469, 0.75174483, 0.79687268, 0.82178998,
       0.70621098, 0.64181127, 0.67322609, 0.68509387, 0.66186814,
       0.66916771, 0.67187304, 0.66492767, 0.68650169, 0.66024745])

## Effect of outliers on mean and median

In [209]:
arr = np.random.randint(1, 100, 100)
arr

array([19, 64, 11, 85, 81, 60, 63,  3, 24, 47, 90,  7, 45, 50, 70, 34, 11,
       65, 80, 37, 79, 12, 30, 25, 63, 75, 86, 14, 56, 52, 81, 43, 54, 74,
       87, 80, 14, 63, 40, 42, 30,  8, 76, 59, 38, 17, 66, 95, 69, 10, 23,
       83, 20, 25, 60, 96, 59, 94, 31, 81, 76, 70, 82,  6, 68, 16, 68, 66,
       19, 68, 61, 12, 26, 83, 89, 72, 21, 25, 74, 49, 42, 69,  8, 68,  5,
       56, 91, 21, 44, 71, 88, 36, 76, 56, 96, 22, 71,  2, 31, 22])

In [210]:
arr.shape

(100,)

In [211]:
np.mean(arr)

50.82

In [212]:
np.median(arr)

56.0

In [213]:
arr_w_outlier = np.append(arr, [1000, 2000])

In [214]:
arr_w_outlier.shape

(102,)

In [215]:
np.mean(arr_w_outlier) # Outliers affect the mean not the median. 

79.23529411764706

In [216]:
np.median(arr_w_outlier) 

57.5

## Effect of scaling arrays on mean and median

In [218]:
arr = np.random.rand(100)
arr

array([0.59252671, 0.86708949, 0.421343  , 0.05495776, 0.1375451 ,
       0.09549212, 0.4709935 , 0.33165668, 0.64703623, 0.50082042,
       0.21503007, 0.51313894, 0.1325744 , 0.572067  , 0.39398331,
       0.78109889, 0.47329122, 0.8467751 , 0.56643127, 0.4430911 ,
       0.60768507, 0.80747548, 0.6851733 , 0.51046572, 0.93042127,
       0.0236477 , 0.44546311, 0.36948843, 0.60392044, 0.63244446,
       0.15741849, 0.99457764, 0.14817776, 0.44597596, 0.3723749 ,
       0.13273025, 0.69609818, 0.5642858 , 0.48866376, 0.2006253 ,
       0.53112111, 0.55484065, 0.923874  , 0.63893561, 0.13175303,
       0.15589729, 0.6563592 , 0.38950819, 0.66845615, 0.19508348,
       0.81480509, 0.8310767 , 0.95028855, 0.88947364, 0.31543679,
       0.96586958, 0.74605075, 0.99320834, 0.29653786, 0.19055782,
       0.72859549, 0.06901062, 0.0670685 , 0.20747363, 0.09004778,
       0.70081173, 0.85432242, 0.16724042, 0.18570498, 0.39763704,
       0.46163824, 0.00143144, 0.57530973, 0.14309162, 0.00820

In [219]:
np.mean(arr)

0.4947117219565867

In [220]:
np.median(arr)

0.4809774912050375

In [221]:
arr1 = 2.5 * arr + 0.65 # scaling by 2.5 nd shifting by .65.

In [223]:
print(np.mean(2.5 * arr + 0.65), # effect of scaling nd shift. on mean 
      2.5 * np.mean(arr) + 0.65)

1.886779304891467 1.886779304891467


In [227]:
print(np.median(2.5 * arr + 0.65), # effect of scaling nd shift. on median
      2.5 * np.median(arr) + 0.65)

1.8524437280125938 1.8524437280125938


In [226]:
print(np.var(2.5 * arr + 0.65), # effect of scaling nd shift. on var. 
      2.5*2.5*np.var(arr))

0.5237853197148404 0.5237853197148404


In [231]:
print(np.std(2.5 * arr + 0.65), # effect of scaling nd shift. on std 
      2.5 * np.std(arr))

0.7237301428811989 0.7237301428811987


In [232]:
arr1 = np.random.rand(100)
arr2 = np.random.rand(100)

In [233]:
print( np.mean(0.21 * arr1 - 0.75 * arr2), 
      0.21 * np.mean(arr1) - 0.75 * np.mean(arr2))

-0.29793595345881335 -0.2979359534588132
