# Introduction to numpy and its functinos 

### Package used in python for matrix, array, vector calculation. 

In [1]:
import numpy as np

In [2]:
# Numpy array - vectors 1d and matrices nd
simplelist=[1,2,3]

In [3]:
simplelist

[1, 2, 3]

In [4]:
# convert the above into array structure. 
np.array(simplelist)

array([1, 2, 3])

In [5]:
# list of list 
simplelist_list=[[1,2,3],[4,5,6],[7,8,9]]

In [6]:
# convert into array struc
np.array(simplelist_list)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
# arange function: 
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [9]:
# Zeroes and ones 
np.zeros(100)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
np.ones(100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [14]:
# linspace - evenly spaced number 
np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

In [17]:
# identity matrix 
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [18]:
# Randomization using numpy 
np.random.rand(3,2) # uniform distribution values. 

array([[0.22198242, 0.61082465],
       [0.87243385, 0.93870433],
       [0.66449201, 0.05836043]])

In [19]:
np.random.randn(2,3) # normal dist values. mean=0 and std dev=1.

array([[-0.37381527, -0.21605982,  0.37722878],
       [-0.51305492, -1.41852355,  0.39122335]])

In [20]:
np.random.randint(2,3) # to get a random integer 2 is inclusive 

2

In [22]:
np.random.randint(2,10,4)

array([8, 2, 7, 6])

In [27]:
sample_array=np.arange(30)

In [31]:
rand_array=np.random.randint(0,100,20)
rand_array

array([63, 22, 71,  6, 86, 10, 53, 15, 98, 32, 49,  3, 66,  7,  4, 59, 48,
       23, 72, 54])

In [29]:
# reshape func
sample_array.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [32]:
rand_array.reshape(4,5)

array([[63, 22, 71,  6, 86],
       [10, 53, 15, 98, 32],
       [49,  3, 66,  7,  4],
       [59, 48, 23, 72, 54]])

In [33]:
# shape func
sample_array.shape

(30,)

In [34]:
# Arg min func
sample_array.argmin() # or .min()

0

In [35]:
sample_array.argmax() # or .max()

29

In [37]:
# Finding the data type 
sample_array.dtype

dtype('int32')

In [43]:
# TRANSPOSING
ed = np.random.randn(2,10)
ed

array([[ 0.12846573,  2.1855858 ,  1.47958137,  0.27204959,  0.41341516,
         1.01719699,  0.45198888, -0.0028776 , -0.17912519, -0.71641933],
       [ 0.29666077,  0.70595385,  0.54152716,  0.95180036, -0.84437358,
        -0.25854302, -1.01266525,  1.67859731,  0.34009064, -0.2745828 ]])

In [44]:
ed.T

array([[ 0.12846573,  0.29666077],
       [ 2.1855858 ,  0.70595385],
       [ 1.47958137,  0.54152716],
       [ 0.27204959,  0.95180036],
       [ 0.41341516, -0.84437358],
       [ 1.01719699, -0.25854302],
       [ 0.45198888, -1.01266525],
       [-0.0028776 ,  1.67859731],
       [-0.17912519,  0.34009064],
       [-0.71641933, -0.2745828 ]])

# How to select group of objects from a particular array

In [46]:
# Indexing
sample_array=np.arange(10,21)

In [47]:
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [48]:
sample_array[9] # pull the value at the 9th position. Indexing starts from 0. 

19

In [49]:
sample_array[2:5] 

array([12, 13, 14])

In [50]:
sample_array[[2,5]] # double square brackets lets you choose separate objects. 

array([12, 15])

In [55]:
sample_array[1:2]=100
sample_array 

array([ 10, 100,  12,  13,  14,  15,  16,  17,  18,  19,  20])

In [57]:
# BROADCASTING - applying value on the existing. 
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [59]:
# subsetting of above 
subset_samp=sample_array[0:7]
subset_samp

array([10, 11, 12, 13, 14, 15, 16])

In [60]:
subset_samp[:]=1001

In [61]:
subset_samp

array([1001, 1001, 1001, 1001, 1001, 1001, 1001])

In [62]:
sample_array # subset_samp=sample_array[0:7] in the above is not a duplication or a copy of sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001,   17,   18,   19,   20])

In [63]:
# COPY 
sample_array=np.arange(10,21)
copy_samplearray=sample_array.copy()

In [66]:
copy_samplearray[0:7]=10

In [67]:
sample_array # we can see the original array was not affected by the change. Thanks to copy() !

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

# Indexing a Matrix

### All values will be similar unlike dataframe

In [68]:
sample_mat=np.array(([50,20,1,23],[24,21,32,23],[34,56,6,89],[98,56,87,9]))

In [69]:
sample_mat # each list is a row in the matrix

array([[50, 20,  1, 23],
       [24, 21, 32, 23],
       [34, 56,  6, 89],
       [98, 56, 87,  9]])

In [72]:
sample_mat[0][3] # first row and 3 column is pulled. using two square brackets.

23

In [74]:
# or
sample_mat[0,3]

23

In [76]:
# SLICING A MATRIX
sample_mat[3,:] # 4th row and all columns. (row, column)

array([98, 56, 87,  9])

In [77]:
sample_mat[3] # 4th row alone.

array([98, 56, 87,  9])

In [81]:
# CUSTOM INDEXING OF MATRICES: 
sample_mat=np.array(([50,20,1,2,23],[24,21,32,34,23],[34,45,56,6,89],[98,45,56,87,9]))

In [82]:
sample_mat

array([[50, 20,  1,  2, 23],
       [24, 21, 32, 34, 23],
       [34, 45, 56,  6, 89],
       [98, 45, 56, 87,  9]])

In [83]:
sample_mat[:,(1,3)] # all rows, first column and 3 column to be extracted. 

array([[20,  2],
       [21, 34],
       [45,  6],
       [45, 87]])

In [85]:
sample_mat[:,(3,1)] # to obtain however you want ie order is not of importance.

array([[ 2, 20],
       [34, 21],
       [ 6, 45],
       [87, 45]])

# Selection Techniques

In [86]:
sample_array=np.arange(1,31)

In [87]:
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [95]:
sample_array < 10 # true where < 10 and false where > 10 

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False])

In [96]:
boole= sample_array < 10 # to obtain the values instead of boolean

In [97]:
sample_array[boole] 

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [98]:
# another method. 
sample_array[sample_array<10]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [99]:
# ARTHMETIC OPERATIONS. direct vector opr. 
sample_array + sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60])

In [100]:
sample_array * sample_array

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676,
       729, 784, 841, 900])

In [101]:
2/sample_array

array([2.        , 1.        , 0.66666667, 0.5       , 0.4       ,
       0.33333333, 0.28571429, 0.25      , 0.22222222, 0.2       ,
       0.18181818, 0.16666667, 0.15384615, 0.14285714, 0.13333333,
       0.125     , 0.11764706, 0.11111111, 0.10526316, 0.1       ,
       0.0952381 , 0.09090909, 0.08695652, 0.08333333, 0.08      ,
       0.07692308, 0.07407407, 0.07142857, 0.06896552, 0.06666667])

In [102]:
# UNIVERSAL ARRAY FUNCTIONS. can be performed on matrices also. 
# sqrt, exponential, mean, max, min, std, var and so on.. 
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595,
       4.58257569, 4.69041576, 4.79583152, 4.89897949, 5.        ,
       5.09901951, 5.19615242, 5.29150262, 5.38516481, 5.47722558])

In [103]:
np.mean(sample_array)

15.5

In [104]:
np.max(sample_array)

30

In [105]:
np.argmax(sample_array) # Argmax and Argmin gives the position of the max and min values respectively. 

29

In [106]:
np.cos(sample_array)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
        0.96017029,  0.75390225, -0.14550003, -0.91113026, -0.83907153,
        0.0044257 ,  0.84385396,  0.90744678,  0.13673722, -0.75968791,
       -0.95765948, -0.27516334,  0.66031671,  0.98870462,  0.40808206,
       -0.54772926, -0.99996083, -0.53283302,  0.42417901,  0.99120281,
        0.64691932, -0.29213881, -0.96260587, -0.74805753,  0.15425145])

In [107]:
np.sin(sample_array)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111,
       -0.99999021, -0.53657292,  0.42016704,  0.99060736,  0.65028784,
       -0.28790332, -0.96139749, -0.75098725,  0.14987721,  0.91294525,
        0.83665564, -0.00885131, -0.8462204 , -0.90557836, -0.13235175,
        0.76255845,  0.95637593,  0.27090579, -0.66363388, -0.98803162])

In [109]:
array = np.random.randn(6,6)

In [110]:
array

array([[ 1.79250919, -1.0440475 , -0.9546054 ,  0.43693423, -0.11835581,
         0.41809993],
       [ 0.23354132,  1.17574701, -0.63497531,  0.88962413,  1.04992395,
        -1.02085499],
       [-0.28036002,  0.37325976,  0.23714712,  0.60208405,  0.01706443,
         0.47128239],
       [-0.9125488 ,  0.79081558, -1.51170876, -0.36735879,  1.92799361,
         0.3766903 ],
       [-1.19722307, -1.31709832, -0.10183178, -0.1694945 , -0.18332736,
        -1.0553513 ],
       [-1.05808753,  1.91526212,  0.46347074, -0.03289204, -1.43327954,
         0.44923294]])

In [111]:
np.round(array) # rounding up 

array([[ 2., -1., -1.,  0., -0.,  0.],
       [ 0.,  1., -1.,  1.,  1., -1.],
       [-0.,  0.,  0.,  1.,  0.,  0.],
       [-1.,  1., -2., -0.,  2.,  0.],
       [-1., -1., -0., -0., -0., -1.],
       [-1.,  2.,  0., -0., -1.,  0.]])

In [112]:
np.round(array, decimals = 2) # rounding up to two decimals 

array([[ 1.79, -1.04, -0.95,  0.44, -0.12,  0.42],
       [ 0.23,  1.18, -0.63,  0.89,  1.05, -1.02],
       [-0.28,  0.37,  0.24,  0.6 ,  0.02,  0.47],
       [-0.91,  0.79, -1.51, -0.37,  1.93,  0.38],
       [-1.2 , -1.32, -0.1 , -0.17, -0.18, -1.06],
       [-1.06,  1.92,  0.46, -0.03, -1.43,  0.45]])

In [113]:
np.var(sample_array)

74.91666666666667

In [114]:
np.std(sample_array)

8.65544144839919

In [115]:
# functions on string values of an array. 
sports=np.array(['golf','foosball','cricket','football','cricket'])

In [116]:
# UNIQUE - to find the unique values, note they are case sensitive. 
np.unique(sports)

array(['cricket', 'foosball', 'football', 'golf'], dtype='<U8')

# Input and output options & saving fles

In [135]:
simple_arr=np.arange(0,20)
print(simple_arr)
print('\n')
print(sample_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]


In [136]:
np.save('sample_array',sample_array) # saves as .npy

In [137]:
np.savez('2 arrays.npz',a=simple_arr,b=sample_array) # archive for more than one array.

In [138]:
np.load('sample_array.npy')

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [139]:
archive=np.load("2 arrays.npz")

In [141]:
archive['a']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [142]:
archive['b']

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [144]:
# to save as text file. 
np.savetxt('text_file.txt',sample_array,delimiter=',')

In [148]:
# to load the text file.
np.loadtxt('text_file.txt',delimiter=',')

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30.])